version: "3.7"

services:
  mysql:
    container_name: MysqlSequelize
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 33068:3306
    expose:
      - 33068
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  web:
    container_name: Apirest
    restart: always
    build: .
    ports:
      - "5000:4000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    links:
      - mysql
